services:
  - type: web
    name: fuel-stations
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_server.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fuel-db
          property: connectionString

databases:
  - name: fuel-db
    plan: free
